### ISSUE TITLE
Connect the OSD to the pulpino

### ISSUE THREAD

**Issue by Liyang131313** [opensocdebug/osd-hw#52]
Hello, can I connect the OSD to the pulpino, is there a reference example of the connection method? @asb @wallento

**Comment by Liyang131313** [comment]
Thank you for your kind reply. I mainly want to use HAM, CDM and CTM. Do I need to modify the processor pipeline to connect these modules? @imphil

**Comment by imphil** [comment]
HAM doesn't exist in the current implementation, CDM isn't fully implemented either (it's missing the software side). CTM is implemented for RISC-V and OpenRISC (mor1kx), and requires trace signals coming out of the CPU core. It doesn't require any modification to the processor pipeline.

**Comment by Liyang131313** [comment]
Thank you for your quick and patient answer.
1. Is there a small project that can be referenced for learning HAM? For example, is there a similar open source project in github?
2, CDM is missing the software side, Then can I design an MCU to automatically control the CDM and CTM to complete the detection function? as shown.
![1547471651 1](https://user-images.githubusercontent.com/35372476/51114823-68b2cd00-1841-11e9-8104-4facc70eaa34.png)

@imphil

**Comment by wallento** [comment]
Hi @Liyang131313,

thanks for your interest. I have porting to pulpino on my TODO list and I am happy to support you directly with it. Supporting pulpino shouldn't be too complex. The trace port is essentially there, so we can add this pretty fast together. We had some work for the CDM before. I am meeting @imphil the next days and will discuss with him.

I will get back to you asap.

Cheers,
Stefan

**Comment by imphil** [comment]
> Is there a small project that can be referenced for learning HAM? For example, is there a similar open source project in github?

What do you mean? There are plenty of other modules which can be used as reference on how to write an OSD module; however the Authentication Module is a bit special and needs to be spec'ed first, so you'd have to do a bit more work here.


> CDM is missing the software side, Then can I design an MCU to automatically control the CDM and CTM to complete the detection function? as shown. 

You could certainly do that. Depending on how your "debug interface" looks like you might not need the osd-sw part with GDB integration for CDM, only access to the raw trace packets. That part is already there and working. (CDM is for OpenRISC only at the moment, you'd need to port it to RISC-V cores first)

**Comment by Liyang131313** [comment]
Thank you so much! ! looking forward your message! May I ask when I can download the version of pulpino? @wallento

**Comment by Liyang131313** [comment]
Thanks Reply,
I originally wanted to use HAM, but HAM doesn't exist in the current implementation. So I want to design a HAM, I hope there are some existing projects to refer to. @imphil

**Comment by imphil** [comment]
> So I want to design a HAM, I hope there are some existing projects to refer to.

Not really. You can look at existing designs in CoreSight and other microcontrollers to get ideas how to implement auth. Once you have done your research on that start by writing the spec for it as part of the osd-doc repository. If you have an early implementation idea you can also open an issue there to discuss your idea first before putting it into a full specification text.

**Comment by Liyang131313** [comment]
I feel that it is more difficult for me to design HAM, then I would like to ask when the official can design the HAM module? @imphil

**Comment by imphil** [comment]
There is no timeline for that since nobody has had the need for this module so far.

**Comment by Liyang131313** [comment]
OK. . Thank you again for your patience. @imphil

**Comment by Liyang131313** [comment]
Depending on how your **"debug interface"** looks like you might not need the osd-sw part with GDB integration for CDM, only access to the raw trace packets. 

 **"debug interface"** 
What kind of debugging interface does my design suggest to use to get the desired signal?
And，how is it convenient for the MCU to process the received  @imphil

**Comment by imphil** [comment]
Your picture is very vague, and only you will be able to decide on the right answer after studying OSD in more detail. However, If you want to have a microcontroller in the loop for automated "debugging" and no desktop PC, manually decoding and using the OSD-generated debug packets might be a good option. You can read more about that in the OSD specification. (http://opensocdebug.readthedocs.io/)

**Comment by Liyang131313** [comment]
Hi @wallento 
Sorry to bother you to rest,Have you completed the transplantation of OSD on pulpino. I am looking forward to your progress and reply.
wish you a happy life!

**Comment by Liyang131313** [comment]
Hello, is there any OSD related ASIC synthesis result? @wallento @imphil

**Comment by imphil** [comment]
@Liyang131313 No, there are no ASIC synthesis results or tapeouts as far as I know.

**Comment by Liyang131313** [comment]
With Design Compiler synthesis tool, is there a combined result of OSD and other RISC processors? If so, can I synthesis the processor of them and then subtract the processor's synthesis result from the total synthesis result to get the OSD hardware resource overhead? @imphil

**Comment by Liyang131313** [comment]
sorry，And Is the joint of OSD and pulpino completed? @imphil

**Comment by imphil** [comment]
@Liyang131313 

- You can synthesize OpTiMSoC with DC and get the results from there. I don't have them handy, unfortunately.
- I haven't seen work on pulpissimo and OSD recently.

**Comment by Liyang131313** [comment]
Ok, I received, thank you for your quick and patient response！ @imphil

**Comment by Liyang131313** [comment]
![default](https://user-images.githubusercontent.com/35372476/53473935-bfe5c780-3aa6-11e9-8a9f-41f028d0ef8d.png)

@imphil  Hello, which of the above two processors can handle the data packets in the OSD more efficiently, and will the hardware multiplier be used to analyze the data packets?

I want to choose one of them as the core of the MCU I designed to receive and analyze the data packets in the OSD.

**Comment by imphil** [comment]
It really depends on your usage scenario, I cannot help you here unfortunately.

**Comment by Liyang131313** [comment]
Ok, thank you for your reply. @imphil

**Comment by Liyang131313** [comment]
Sorry to bother again. Can I design an “AXI Trace module”? The ATM can perform behavior analysis on the signals on the AXI bus, determine the read or write behavior of the current access, and send the tracked bus information to the Debug interface as a data packet. @imphil

**Comment by Liyang131313** [comment]
Hello, I am very looking forward to your reply, has you completed the connection between OSD and pulpino? @wallento

**Comment by imphil** [comment]
@wallento isn't currently working on this project as far as I know. Please give it a try yourself and let me know if you get stuck.

**Comment by Liyang131313** [comment]
Okay thank you. @imphil
